[build]
  publish = "."
  functions = "netlify/functions"
  command = "echo 'deploy'"

[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "SAMEORIGIN"
    X-Content-Type-Options = "nosniff"
